=== DeKaN/mediateka/XML/discs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="mediateka" targetNamespace="mediateka" xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified">
  <xs:element name="discs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="disc" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="autoIndex" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="disc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ownerID"/>
        <xs:element ref="format"/>
        <xs:element ref="regionCode"/>
        <xs:element ref="isPresent"/>
		<xs:element ref="films"/>
      </xs:sequence>
      <xs:attribute name="discID" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ownerID" type="xs:nonNegativeInteger"/>
  <xs:element name="format" type="xs:string"/>
  <xs:element name="regionCode" type="xs:nonNegativeInteger"/>
  <xs:element name="isPresent" type="xs:boolean"/>
  <xs:element name="films">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="filmID" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="filmID" type="xs:string"/>
</xs:schema>

=== DeKaN/mediateka/src/mediateka/XML/discs.xml
<?xml version="1.0" encoding="utf-8"?>
<discs xmlns="mediateka" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="mediateka discs.xsd" autoIndex="3">
   <disc discID="1">
		<ownerID>1</ownerID>
		<format>DVD</format>
		<regionCode>3</regionCode>
        <isPresent>false</isPresent>
	</disc>
	<disc discID="2">
	<ownerID>1</ownerID>
		<format>Blu-ray</format>
		<regionCode>2</regionCode>
		<isPresent>true</isPresent>
	</disc>
</discs>

=== DeKaN/mediateka/XML/discs.xml
<?xml version="1.0" encoding="UTF-8"?>

<discs xmlns="mediateka" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="mediateka discs.xsd" autoIndex="4">
  <disc discID="1">
    <ownerID>0</ownerID>
    <format>DVD</format>
    <regionCode>0</regionCode>
    <isPresent>false</isPresent>
    <films>
           <filmID>1</filmID>
    </films>
  </disc>
  <disc discID="2">
    <ownerID>0</ownerID>
    <format>BD</format>
    <regionCode>0</regionCode>
    <isPresent>true</isPresent>
    <films>
           <filmID>1</filmID>
           <filmID>2</filmID>
    </films>
  </disc>
  <disc discID="3">
    <ownerID>0</ownerID>
    <format>DVD</format>
    <regionCode>2</regionCode>
    <isPresent>true</isPresent>
    <films>
           <filmID>3</filmID>
    </films>
  </disc>
</discs>
