=== DeKaN/mediateka/XML/films.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="mediateka" targetNamespace="mediateka" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
    <xs:element name="films">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="film" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="autoIndex" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="film">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="russianTitle"/>
                <xs:element ref="englishTitle"/>
                <xs:element ref="year"/>
                <xs:element ref="description"/>
                <xs:element ref="genres"/>
                <xs:element ref="countries"/>
                <xs:element ref="comment"/>
                <xs:element ref="length"/>
                <xs:element ref="rating"/>
                <xs:element ref="subtitles"/>
                <xs:element ref="cover"/>
                <xs:element ref="soundLanguages"/>
                <xs:element ref="isSeen"/>
            </xs:sequence>
            <xs:attribute name="filmID" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="russianTitle" type="xs:string"/>
    <xs:element name="englishTitle" type="xs:string"/>
    <xs:element name="year" type="xs:nonNegativeInteger"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="genres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genre" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="genre" type="xs:string"/>
    <xs:element name="countries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="country" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="country" type="xs:string"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="length" type="xs:nonNegativeInteger"/>
    <xs:element name="rating" type="xs:nonNegativeInteger"/>
    <xs:element name="subtitles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="subtitle" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subtitle" type="xs:string"/>
    <xs:element name="cover" type="xs:base64Binary"/>
    <xs:element name="soundLanguages">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="soundLanguage" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="soundLanguage" type="xs:string"/>
    <xs:element name="isSeen" type="xs:boolean"/>
</xs:schema>

=== DeKaN/mediateka/XML/films.xml
<?xml version="1.0" encoding="utf-8"?>
<films xmlns="mediateka"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="mediateka films.xsd" autoIndex="3">
  <film filmID="1">
    <russianTitle>123</russianTitle>
    <englishTitle>321</englishTitle>
    <year>2000</year>
    <description>qwerty</description>
    <genres>
      <genre>qwe</genre>
      <genre>qdfe</genre>
      <genre>qdfe</genre>
    </genres>
    <countries>
      <country>rty</country>
      <country>qwerty</country>
    </countries>
    <comment/>
    <length>120</length>
    <rating>5</rating>
    <subtitles>
      <subtitle>123</subtitle>
      <subtitle>re</subtitle>
    </subtitles>
    <cover>dGVzdA==</cover>
    <soundLanguages>
      <soundLanguage>123</soundLanguage>
      <soundLanguage>gf</soundLanguage>
    </soundLanguages>
    <isSeen>false</isSeen>
  </film>
  <film filmID="2">
    <russianTitle>456</russianTitle>
    <englishTitle>645</englishTitle>
    <year>2001</year>
    <description>asd</description>
    <genres>
      <genre>rty</genre>
    </genres>
    <countries>
      <country>rty</country>
    </countries>
    <comment>asd</comment>
    <length>130</length>
    <rating>3</rating>
    <subtitles>
      <subtitle>123</subtitle>
    </subtitles>
    <cover>dGVzdA==</cover>
    <soundLanguages>
      <soundLanguage>123</soundLanguage>
    </soundLanguages>
    <isSeen>false</isSeen>
  </film>
</films>
