=== DeKaN/mediateka/XML/history.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="mediateka" targetNamespace="mediateka" xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="history">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="record" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="autoIndex" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="record">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="discID"/>
                <xs:element ref="personID"/>
                <xs:element ref="comment"/>
                <xs:element ref="dateOfIssue"/>
                <xs:element ref="dateOfReturn"/>
                <xs:element ref="promisingDate"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="discID" type="xs:positiveInteger"/>
    <xs:element name="personID" type="xs:positiveInteger"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="dateOfIssue" type="xs:date"/>
    <xs:element name="dateOfReturn" type="xs:date"/>
    <xs:element name="promisingDate" type="xs:date"/>
</xs:schema>

=== DeKaN/mediateka/XML/history.xml
<?xml version="1.0" encoding="utf-8"?>
<history xmlns="mediateka"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="mediateka history.xsd" autoIndex="4">
   <record recordID="1">
		<discID>1</discID>
		<personID>1</personID>
		<comment>qwerty</comment>
		<dateOfIssue>2011-01-01</dateOfIssue>
		<dateOfReturn>2011-02-01</dateOfReturn>
		<promisingDate>2011-01-12</promisingDate>
	</record>
	<record recordID="2">
		<discID>3</discID>
		<personID>2</personID>
		<comment>qwerty</comment>
		<dateOfIssue>2011-01-01</dateOfIssue>
		<dateOfReturn>2011-02-01</dateOfReturn>
		<promisingDate>2011-02-01</promisingDate>
	</record>
	<record recordID="3">
		<discID>2</discID>
		<personID>3</personID>
		<comment>qwerty</comment>
		<dateOfIssue>2011-01-01</dateOfIssue>
		<dateOfReturn>2011-02-01</dateOfReturn>
		<promisingDate>2011-02-01</promisingDate>
	</record>
</history>
