=== DeKaN/mediateka/XML/persons.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="mediateka" targetNamespace="mediateka" xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified">
  <xs:element name="persons">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="person" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="autoIndex" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="person">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstName"/>
        <xs:element ref="lastName"/>
        <xs:element ref="secondName"/>
        <xs:element ref="phoneNumber"/>
      </xs:sequence>
      <xs:attribute name="personID" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="firstName" type="xs:string"/>
  <xs:element name="lastName" type="xs:string"/>
  <xs:element name="secondName" type="xs:string"/>
  <xs:element name="phoneNumber" type="xs:string"/>
</xs:schema>

=== DeKaN/mediateka/XML/persons.xml
<?xml version="1.0" encoding="utf-8"?>
<persons xmlns="mediateka"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="mediateka persons.xsd" autoIndex="3">
    <person personID="1">
        <firstName>Alex</firstName>
        <lastName>John</lastName>
        <secondName>Smith</secondName>
        <phoneNumber>12345678</phoneNumber>
        <comment>SomeComment1</comment>
    </person>
    <person personID="2">
        <firstName>Mitrich</firstName>
        <lastName>Alex</lastName>
        <secondName>Smith</secondName>
        <phoneNumber>12345678</phoneNumber>
        <comment>SomeComment2</comment>
    </person>
</persons>
